version: "3.8"

services:
  express-app:
    image: todo-backend-dev
    container_name: todo-backend-dev
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    command: nodemon ./app.js
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      #  - MONGO_URL=mongodb://the_username:the_password@localhost:3456/the_database
      - REDIS_URL=//redis:6379
    #      - REDIS_URL="//localhost:6378"
    volumes:
      - .:/express-app
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - redis
    networks:
      - backend_frontend_network

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
      #- 3456:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=the_username
      - MONGO_INITDB_ROOT_PASSWORD=the_password
      - MONGO_INITDB_DATABASE=the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
    #      - ./mongo_data:/data/db
    networks:
      - backend_frontend_network

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
      #- 6378:6379
    command: ["redis-server", "--appendonly", "yes"] # Overwrite the CMD
    volumes: # Declare the volume
      - ./redis_data:/data
    networks:
      - backend_frontend_network

  #debug-helper:
  #  image: busybox

volumes:
  mongo_data:
  redis-data:

networks:
  backend_frontend_network:
    name: backend_frontend_network
    external: true
    #driver: bridge
