version: "3.8"

services:
  app:
    image: todo-frontend-prod
    build:
      context: .
      dockerfile: .docker/client.prod.Dockerfile
    environment:
      - VITE_BACKEND_URL=http://localhost:80/api
    container_name: todo-frontend-prod
    ports:
      - 8080:80
    networks:
      - backend_frontend_network

  express-app:
    image: todo-backend-prod
    container_name: todo-backend-prod
    build:
      context: .
      dockerfile: .docker/server.prod.Dockerfile
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - REDIS_URL=//redis:6379
    networks:
      - backend_frontend_network

  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=the_username
      - MONGO_INITDB_ROOT_PASSWORD=the_password
      - MONGO_INITDB_DATABASE=the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - /todo-backend/mongo_data:/data/db
    networks:
      - backend_frontend_network

  redis:
    image: redis
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./todo-backend/redis_data:/data
    networks:
      - backend_frontend_network

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    container_name: reverse-proxy
    depends_on:
      - app
      - express-app
    networks:
      - backend_frontend_network

volumes:
  mongo_data:
  redis-data:

networks:
  backend_frontend_network:
    name: backend_frontend_network
